#2019071 19106 2019110
wantTerm=26061
# 0:ssq 1:dlt 3:3d
loteType=1
# 0:normal 1:ender or 3d 2:sport:double blue  3:blue
dataType=0
trainEpoch=5
popNum=50
threadNum=30
netThreadNum=30
nbThreadNum=5
runTimesInner=200
debugFlgLev2=false
settingSuit=7
lastScoreFlg=false
# ssq 5,5 dlt 5,5 3d 5,60
testTerm=5
testSpan=5
#14 13 21 20 33 31 28 27 8 5 7 4 3 2 6 1 10 11
any=6 3 2 4 7 5 33 27 28 31
#5,5,40,40,80,80 6,6,5,5,4,4,3,3
testTermArr=3,20,5,5,5,5,5
#5,5,40,40,80,80
testSpanArr=30,30,20,20,10,10,5
testTermArrSq=5,5,5,5,5,5,5
#30,30,20,20,10,10,5
testSpanArrSq=30,30,30,30,30,30,30
testTermArrEnder=3,8,8,8,8,8,8,8
#30,30,30,30
testSpanArrEnder=30,30,30,30,30,30,30,30
testTermArrB=5,12,12,12,12
testSpanArrB=96,24,24,24,24
testTermArrAny=15,15,10,10,5,5
testSpanArrAny=5,5,5,5,5,5
# dlt:22 ssq:21
emptyCnt=3
#split=28,28,23,23,18,18,13,13  27,27,27,27,27,27 27,27,24,24,21,21 6,6,4 30,30,27,27,24,24  ori:13
split=13,6,4,4,4
#14,14,11,11,8,8
splitAny=8,8,6,6,4,4
#6,6,4 28,28,25,25,22,22,16,16
splitSq=9,6,4,4,4
splitEnder=6,8,8,8,8
splitB=5,12,10,10,8
nextT=0
processEchoFlg=0
testCnt=2000
typeTimesFlg=0
#timesFlg=true oddFlg=0 way3Flg=0 div3Flg=0 way5Flg=true bigSmallFlg=0 hisSeeCnt=2 numLayer=1 numHidden=2
timesFlg=true
oddFlg=0
way3Flg=0
div3Flg=0
way5Flg=0
bigSmallFlg=0
hisSeeCnt=3
numLayer=2
#numHidden=2
numHidden=2
# net = 9 balance   sport net=3   blue net =4  ace,3d=1
netCnt=3
otherPopPercent=0.3
numElite=0.05
numEliteCopies=1
addNewPopWhenPercent=0.25
displayEveryCnt=30
#gatherType=0 frontOkType=1
gatherType=0
frontOkType=1
#gatherType=4
#frontOkType=0
lineRight=0
termSpanSameType=1
#n1=8
#n2=3
n1=10
n2=4
validateCnt=1800
dynaTestTerm=0
frontValidForKill=4
dynaTestSelect=1
dynaTestMulti=1
dynaTestRemain=0
wrongMode=true
wrongModeOffSet=20
formulScope=26 35 20 32 30 7 22 10 1 34 24 2 14 19 8 15 4 21 17 5 23 31 12 11 28 29 13 27
#S-sum, W-width, H- history S,W,RH0,SH1 E-enderSum   H0 ~ now his, H1 ~ before now his 1  ori:RS,RW,RSH1,RWH1,RV  for~RG RV,RH0
#flexNet=RS,RW,RSH1,RWH1,RV
#flexOutPut=R
#flexNet=BS,BW,BSH1,BWH1,BV
flexOutPut=RW
#1:no debug 0:debug
flexNoDebug=0
#for sum:30,35 (40,50) width:50,30 blueSum:40,5,0.002~30,15  forRW:term5 forRG:term10
flexTerm=5
flexType=1
#90
flexHd=100
flexMinR=0.03
flexJobCnt=2
flexThd=2